# -*- coding: utf-8 -*-
{
    	'name': 'Backend Theme Enterprise',

	'summary': """

""",

	'description': """

    """,
    'author': "Tele INC.",
    'website': "https://www.tele.studio",
    'license': 'TPL-1',
    'version': '1.0.1.0.0',
    'category': 'Themes/Backend',
    'depends': ['web', 'base_setup', 'mail', 'auth_signup', 'tele_enterprise', 'tele_studio'],

    # always loaded
    'data': [
        'data/data.xml',
        'data/ks_drawer_colors.xml',
        'data/ks_color_theme.xml',
        'security/ir.model.access.csv',
        'security/curved_theme_security.xml',
        'views/views.xml',
        'views/ks_main_panel.xml',
        'views/templates.xml',
        'views/ks_assets_popup_animation.xml',
        'views/ks_login_page.xml',
        'views/ks_res_users_preferences.xml',
        'views/ks_res_config_settings_view.xml',
    ],
    'images': [
        'static/description/banner.gif',
        'static/description/list_screenshot.gif',
    ],
    'assets': {
        'web.assets_qweb': [
            '/tele_backend_theme/static/src/xml/ks_menu.xml',
            '/tele_backend_theme/static/src/xml/ks_left_sidebar_panel.xml',
            '/tele_backend_theme/static/src/xml/ks_switch_language.xml',
            '/tele_backend_theme/static/src/xml/ks_quick_settings.xml',
            '/tele_backend_theme/static/src/xml/ks_global_settings.xml',
            '/tele_backend_theme/static/src/xml/ks_fullscreen.xml',
            # '/tele_backend_theme/static/src/xml/ks_search_panel.xml',
            '/tele_backend_theme/static/src/xml/ks_company_settings.xml',
            '/tele_backend_theme/static/src/xml/ks_bookmark.xml',
            '/tele_backend_theme/static/src/xml/ks_appdrawer_edit.xml',
            '/tele_backend_theme/static/src/xml/ks_calendar_view.xml',
            '/tele_backend_theme/static/src/xml/ks_image_template.xml',
            '/tele_backend_theme/static/src/xml/ks_login_background_color.xml',
            '/tele_backend_theme/static/src/xml/ks_login_background_image.xml',
            '/tele_backend_theme/static/src/xml/ks_menubar_darkmode_toggle.xml',
            '/tele_backend_theme/static/src/xml/ks_leftpanelmenu.xml',
            '/tele_backend_theme/static/src/xml/ks_userMenu.xml',
            '/tele_backend_theme/static/src/xml/ks_navbar.xml',
            '/tele_backend_theme/static/src/xml/ks_action_menus.xml',
            '/tele_backend_theme/static/src/xml/ks_systray.xml',
            '/tele_backend_theme/static/src/xml/ks_home_menu.xml',
            '/tele_backend_theme/static/src/js/widgets/ksListDocumentViewer.xml',
            # '/tele_backend_theme/static/src/xml/Ks_throbber_inherit.xml',
        ],
        'web._assets_primary_variables': [
            '/tele_backend_theme/static/src/scss/abstracts/tele_primary_variables.scss',
        ],
        'web.assets_backend': [
            '/tele_backend_theme/static/src/scss/abstracts/variables.scss',
            '/tele_backend_theme/static/src/scss/base/fonts.scss',
            '/tele_backend_theme/static/src/scss/base/default.scss',
            '/tele_backend_theme/static/src/scss/base/animation.scss',
            '/tele_backend_theme/static/src/scss/base/forms.scss',
            '/tele_backend_theme/static/src/scss/base/fields.scss',
            '/tele_backend_theme/static/src/scss/abstracts/mixins.scss',
            '/tele_backend_theme/static/src/scss/abstracts/placeholder.scss',
            '/tele_backend_theme/static/src/scss/components/buttons.scss',
            '/tele_backend_theme/static/src/scss/components/color_theme.scss',
            '/tele_backend_theme/static/src/scss/components/tabs.scss',
            '/tele_backend_theme/static/src/scss/components/table.scss',
            '/tele_backend_theme/static/src/scss/components/form-control.scss',
            '/tele_backend_theme/static/src/scss/components/checkbox.scss',
            '/tele_backend_theme/static/src/scss/components/loaders.scss',
            '/tele_backend_theme/static/src/scss/components/Breadcrumb.scss',
            '/tele_backend_theme/static/src/scss/layout/header.scss',
            '/tele_backend_theme/static/src/scss/layout/apps-drawer.scss',
            '/tele_backend_theme/static/src/scss/layout/ks_quick_settings.scss',
            '/tele_backend_theme/static/src/scss/layout/sidebar.scss',
            '/tele_backend_theme/static/src/scss/layout/bookmark.scss',
            '/tele_backend_theme/static/src/scss/layout/ks_control_panel.scss',
            '/tele_backend_theme/static/src/scss/layout/ks_form_view.scss',
            '/tele_backend_theme/static/src/scss/layout/ks_view.scss',
            '/tele_backend_theme/static/src/scss/layout/ks_vertical_menus.scss',
            '/tele_backend_theme/static/src/scss/responsive/ipad_responsive.scss',
            '/tele_backend_theme/static/src/scss/responsive/phone_responsive.scss',
            '/tele_backend_theme/static/src/scss/pages/discuss.scss',
            '/tele_backend_theme/static/src/scss/pages/calendar.scss',
            '/tele_backend_theme/static/src/scss/pages/all_apps.scss',
            '/tele_backend_theme/static/src/lib/owl.carousel.min.css',
            '/tele_backend_theme/static/src/scss/components/ks_custom_tooltip.css',

            # js assets
            '/tele_backend_theme/static/src/Components/ks_dropdown_menu.js',
            '/tele_backend_theme/static/src/Components/Ks_custom_action_menu.js',
            '/tele_backend_theme/static/src/js/Ks_control_panel_inherit.js',
            '/tele_backend_theme/static/src/js/ks_searchbar.js',
            '/tele_backend_theme/static/src/js/Ks_controlpanel_view.js',
            '/tele_backend_theme/static/src/js/splitview/KsAbstractControllerInherit.js',
            '/tele_backend_theme/static/src/js/widgets/ksListDocumentViewer.js',
            # '/tele_backend_theme/static/src/js/splitview/KsActionManagerInherit.js',
            '/tele_backend_theme/static/src/js/KsWebFrameWork_inherit.js',
            '/tele_backend_theme/static/src/js/ks_app_sidebar.js',
            '/tele_backend_theme/static/src/js/ks_left_sidebar_panel.js',
            '/tele_backend_theme/static/src/js/ks_switch_language.js',
            '/tele_backend_theme/static/src/js/ks_darkmode_toggle.js',
            '/tele_backend_theme/static/src/js/ks_bookmarks_menu.js',
            '/tele_backend_theme/static/src/js/ks_quick_settings_widget.js',
            '/tele_backend_theme/static/src/js/ks_appsmenu.js',
            '/tele_backend_theme/static/src/js/ks_fullscreen.js',
            '/tele_backend_theme/static/src/js/ks_search_panel.js',
            '/tele_backend_theme/static/src/js/views/list/ks_list_renderer.js',
            '/tele_backend_theme/static/src/js/views/form/ks_form_render.js',
            '/tele_backend_theme/static/src/js/ks_global_config_widget.js',
            '/tele_backend_theme/static/src/js/ks_company_config_widget.js',
            '/tele_backend_theme/static/src/js/ks_appdrawer_edit.js',
            '/tele_backend_theme/static/src/js/ks_click_to_edit.js',
            '/tele_backend_theme/static/src/js/ks_abstract_web_client.js',
            '/tele_backend_theme/static/src/js/ks_data_manager.js',
            '/tele_backend_theme/static/src/js/ks_zoom_btn_visibility.js',
            '/tele_backend_theme/static/src/js/ks_calendar_view.js',
            '/tele_backend_theme/static/src/js/ks_relation_fields.js',
            '/tele_backend_theme/static/src/js/views/form/ks_form_controller.js',
            '/tele_backend_theme/static/src/js/views/list/ks_list_controller.js',
            '/tele_backend_theme/static/src/js/ksAbstractController.js',
            '/tele_backend_theme/static/src/js/ks_activity_controller.js',
            '/tele_backend_theme/static/src/js/views/kanban/ks_kanban_controller_inherit.js',
            # '/tele_backend_theme/static/src/js/views/graph/ks_graph_controller_inherit.js',
            # '/tele_backend_theme/static/src/js/views/pivot/ks_pivot_controller_inherit.js',
            '/tele_backend_theme/static/src/js/views/calendar/ks_calendar_controller_inherit.js',
            '/tele_backend_theme/static/src/js/ks_web_client.js',
            '/tele_backend_theme/static/src/lib/owl.carousel.min.js',
            '/tele_backend_theme/static/src/js/app.js',
            '/tele_backend_theme/static/src/js/ks_home_menu.js',
            '/tele_backend_theme/static/src/js/sw.js',
        ],
        'web.assets_frontend': [
            '/tele_backend_theme/static/src/scss/pages/ks_login.scss',
        ],

    },

    "application": True,
    "installable": True,
}
